#!/bin/sh
# This script runs automatically after a git pull or git merge
echo "--- [NexTrip] Automatically updating database ---"
php artisan migrate --force
php artisan db:seed --class=CategorySeeder --force
php artisan db:seed --class=DestinationSeeder --force
echo "--- [NexTrip] Sync complete! ---"
